### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by lsfcin** [ThatOneCheetah/CSGL#2] opened 2017-10-22 20:00 UTC
Hi, I'm trying to use CSGL without luck. Created a project as you instructed and added your code there. Everything compiles but crashes on the third line of code:
`CSGL.Glfw3.glfwWindowHint(CSGL.Glfw3.GLFW_CONTEXT_VERSION_MAJOR, 4);`

I've dropped the glfw3.dll in the .exe folder so I think it is loaded.

...

Could you provide a small sample project so we can work with?

Thanks in advance,
Lucas.

**Comment by ThatOneCheetah** [comment] 2017-10-22 22:00
Could you provide any more detail on the error you're receiving?
Also, if you can, launch the program with a console window attached; this way you can tell whether GLFW loads properly, if it either prints:
 
```Failed to link 'binary.ext'```
  
```Could not resolve 'delegateName' in loaded assembly 'binary.ext'``` ( a bunch )
  
Or if it links any binary to a NULL handle; something went wrong in the process of loading the binaries, and you might have to double check that you have an up-to-date version of either `libglfw` or your graphics drivers.

**Comment by lsfcin** [comment] 2017-10-23 13:55
I'm using glfw 3.2.1 pre-built dll.

This is the exception:

> Managed Debugging Assistant 'PInvokeStackImbalance'  occurred
> Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'project-name!CSGL.Glfw3+PFNGLFWWINDOWHINTPROC::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
> 

This is what my console window shows: 

> Linked 'glfw3.dll' -> '0x675A0000'

**Comment by ThatOneCheetah** [comment] 2017-10-25 17:47
That is odd, because the signatures [seem to match](https://github.com/ThatOneCheetah/CSGL/blob/master/src/CSGL.cs#L447).

Are you sure your `glfw.dll` and project are targeting the same platform?

This error might occur if your `glfw.dll` targets a 64-bit platform, and your application targets a 32-bit platform. `AnyCPU` might also cause issues with invoking unmanaged binaries; please make sure that you are targeting either `x86` or `x64`, and that your targeted platform matches the platform `glfw3.dll` targets.

**Comment by ThatOneCheetah** [comment] 2017-11-12 02:02
Did you manage to get CSGL to work for you?

I will close this issue if it remains unanswered for 30 days.

As for examples, the readme covers the initialization of CSGL, beyond that you could apply any OpenGL/GLFW code, and as there are plenty tutorials on those I doubt my limited OpenGL knowledge could create sufficient examples.

**Comment by ThatOneCheetah** [comment] 2017-11-23 10:56
Issue closed due to inactivity. If this problem persists, please comment to re-open.

**Comment by WolfHybrid23** [comment] 2019-07-02 18:50
I can confirm this is an issue:

I configured my project towards x86 and have tried both Glfw 3.3 and 3.2.1, Both times this issue has occurred. Whenever I run the project with a Glfw 3.2.1 DLL this happens in the console:
```
Linked 'glfw3.dll' -> '0x62FB0000'
```
And it crashes with this error:
```
+PFNGLFWWINDOWHINTPROC::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
```

When I run it with 3.3:
```
Linked 'glfw3.dll' -> '0x5CF70000'
```
And it crashes with this error:
```
+PFNGLFWWINDOWHINTPROC::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
```

I don't have much experience working between Managed to Unmanaged code. So this might be oversight on my part but I would like to get this working, for faster contact you can add me on discord: `WolfHybrid23#4902`

**Comment by ThatOneCheetah** [comment] 2019-07-02 19:31
This seems to be caused by a calling convention mismatch. This oversight is on me, and the fact that calling conventions in 32-bit code are somewhat of an unintelligible mess.

**Closed** 2019-07-02 19:34 UTC
Labels: question
